### ISSUE TITLE
Satoshi Nakamoto - "My Reveal"

### ISSUE THREAD

**Issue by kenorb** [carlos8f/searching-for-satoshi#7]
See: https://satoshinrh.com/

> Please join me as I end my anonymity in a three-part daily series “My Reveal” that begins today, Aug. 18 – the 11th anniversary of my registration of the domain name bitcoin.org. In “My Reveal,” I will divulge such previously unknown facts as the origin of my iconic pseudonym, the status of my 980,000 bitcoins, and my real-life identity. I’ll also introduce Tabula Rasa, my clean-slate vision for the future of Bitcoin. 

> The first of a three-part series in which I, Satoshi Nakamoto, disclose previously unknown facts about the creation of Bitcoin.  I also reveal the developments that led to my departure and why I’m returning to Bitcoin after a decade of total anonymity.

> My birth name is Bilal Khalid.  I used that name to register the domain name theBCCI.net on the 18th of November 2008.  I’ve since changed my legal forename and surname to James Caan.  I updated my name on the domain registration of theBCCI.net since only the owner of the domain can make such a change.  But it is impossible for anyone to change the domain name itself or the date on which it was registered. 

----

Related: https://twitter.com/fluffypony/status/1163185816237150208

**Comment by xluxeq** [comment]
🥇

**Comment by kenorb** [comment]
http://web.archive.org/web/20191030173429/https://satoshinrh.com/
